Ext.define('Appsetup.appsetup.shared.com.model.organization.contactmanagement.SocialCommunicationModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "socialId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "commtype",
          "reference": "SocialCategory",
          "defaultValue": ""
     }, {
          "name": "social",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});